### ISSUE TITLE
MongoDB Id

### ISSUE THREAD

**Issue by Eslem** [BlueEastCode/loopback-graphql-relay#31]
I have my models connected to MongoDB but i get the ids wrong, i receive the id like:'UG9zdDo1YThmMmE2ODkzOWZkZDM5Yjg1ZTdmOTU=' and a normal MongoDB id is:'5a8f2a68939fdd39b85e7f8d'

Also i'm willing to contribute and give support but i cannot find the documentation.

**Comment by ghulamhussain** [comment]
Hi Eslem loopback-graphql-relay encodes  MongoDB id like '5a8f2a68939fdd39b85e7f8d' to base 64 and after conversion the id becomes like UG9zdDo1YThmMmE2ODkzOWZkZDM5Yjg1ZTdmOTU= you can convert it back in your app using graphql-relay use import { fromGlobalId } from 'graphql-relay';
and then convert it in mongodb by using "fromGlobalId(product[key].node.product._options.id).id)",also 
https://www.base64encode.org/ is site where you can encode or decode your ids

**Comment by Eslem** [comment]
Hello,
Sorry i'm new to use this, why is that conversion? is there a way to prevent it?

**Comment by ghulamhussain** [comment]
@Eslem Relay requires records to have a globally unique value for the id field if it exists on an object, so that the record can be identified in the cache.The Node interface has one field id and Relay expects it to be the unique ID that it can use to refetch the object using the node(id) root field.A common approach is to base64 encode ":" as the id, for all types in the schema.Also note that base64 encoding the ID is not mandatory. The only requirement for the id is that it's globally unique. But if your IDs are only unique within a single type, base64 encoding the type and that ID just happens to be a simple way to make them globally unique.

**Comment by kruyvanna** [comment]
@Eslem Thanks for the great work.
In case all my Ids are unique, where can I turn base64 encoding off?
Thanks

**Comment by kruyvanna** [comment]
@Eslem  I am starting to understand that I should use Relay instead of Apollo client so that I dont have to worry about the Id thing. 
Am I right?
